small fixes

diff --git a/bash/argparse b/bash/argparse
--- a/bash/argparse
+++ b/bash/argparse
@@ -1,9 +1,28 @@
+#!/bin/bash
+function usage {
+	[[ -n "$1" ]] && printf "ERROR: %s\n\n" "$1" >&2
+	printf "Usage: <prog_name> [-d] <file>\n" >&2
+	[[ -n "$1" ]] && exit 1
+	exit 0
+}
+
+DEBUG=0
+while getopts ":hd" OPT; do
+	case "$OPT" in
+	"?" | "h") usage ;;
+	"d") DEBUG=1 ;;
+	esac
+done
+shift $((OPTIND - 1))
+
+(($# == 0)) && usage
+(($# > 1)) && usage "Too many files"
 
 # function functiona_dofoo(some_arg){...}
 # function functiona_help(){...}
 
-[[ -z "${1-}" ]] && function_help "$0"
-case $1 in
-	dofoo|bar|baz|...|...) function_"$1" "${@:2}" ;;  # if unction take an argument
-	*) function_help "$0" ;;
-esac
+# [[ -z "${1-}" ]] && function_help "$0"
+# case $1 in
+# dofoo|bar|baz|...|...) function_"$1" "${@:2}" ;;  # if unction take an argument
+# *) function_help "$0" ;;
+# esac
